# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed1dc13696d419e54d894268d4d17c3338ac1b5e4bffbfdf71269ae220dd4993fe0da91e8fa67a73d8c4ed8a8a0de58a91d09bc3a8f09c61d831a9a14b676ae6

test:
  secret_key_base: c4dc08782f2ad2e6a704612e91b43452d8b7db53f17f408235c7aa90f13173e57d1bb32bab190d86296bb0c1a719395e2fdbb7d2281a3c8665a21ec462426de7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
